---
#=====
# EPEL External Repository installation/removal
#=====
- include_tasks: repo/use.yml
  when: epel_use_remote_repositories

- include_tasks: repo/not_use.yml
  when: not epel_use_remote_repositories


#=====
# EPEL Key installation
#=====
- include_tasks: keys/install.yml
  when: epel_install_gpg_key
