---
- name: EPEL | Configure EPEL Repos
  block:

    #=====
    # EPEL External Repository installation/removal
    #=====
    - include_tasks: repo/use.yml
      when: epel_use_remote_repositories

    - include: repo/not_use.yml
      when: not epel_use_remote_repositories

    #=====
    # EPEL Key installation
    #=====
    - include: keys/install.yml
      when: epel_install_gpg_key
  when: ansible_distribution == "RedHat" 
