---
- name: EPEL | Copy EPEL keys to PKI
  copy:
    src: "RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    owner: root
    group: root
    mode: 0600
    backup: yes
 
- name: EPEL | Import EPEL key to RPM db
  tags: [ configuration, repos ]
  rpm_key: 
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
