---
- name: EPEL | Install epel yum repository
  tags: [ configuration, repos ]
  yum_repository:
    name: epel
    description: EPEL repo
    mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch"
    failovermethod: priority
    enabled: "{{ epel_repository_enabled }}"
    gpgcheck: yes
    state: present
